sampler: tpe
n_trials: 10
direction: maximize
objective: val_auroc

search_space:
  task.num_time_steps:
    type: categorical
    choices: [5, 10, 20]
  task.num_noise_samples:
    type: categorical
    choices: [5, 10, 20]
